import type { AppState } from "./types";

export const SAJRA_SEED_STATE: AppState = {
  "appName": "Sajra",
  "language": "en",
  "theme": "light",
  "members": [
    {
      "id": 1,
      "name": "Aiman Sakin MohaddiPur",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Mohamadipur, Zila Azamgrah",
      "photo": null,
      "bio": "",
      "fatherId": null,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 09:58:12"
    },
    {
      "id": 2,
      "name": "Mangal Sakin Amilo",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 1,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:00:34"
    },
    {
      "id": 3,
      "name": "Chandan Mohajir Amilo",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "Mohajir Amilo",
      "fatherId": 1,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:00:34"
    },
    {
      "id": 4,
      "name": "Haji Manullah",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 3,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:09:16"
    },
    {
      "id": 5,
      "name": "Abdul Wahid I",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 3,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:11:38"
    },
    {
      "id": 6,
      "name": "moeen Khalifa",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 3,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:21:59"
    },
    {
      "id": 7,
      "name": "Andul Wajid",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 3,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:27:23"
    },
    {
      "id": 8,
      "name": "Haji Noor mohammad",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 3,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:28:25"
    },
    {
      "id": 9,
      "name": "Mohad Salim Makuni",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 4,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:31:42"
    },
    {
      "id": 10,
      "name": "Mohd Raees Makuni",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 4,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:32:59"
    },
    {
      "id": 11,
      "name": "Abdul Kuddus",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 10,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:34:04"
    },
    {
      "id": 12,
      "name": "Abdullah",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 11,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:36:59"
    },
    {
      "id": 13,
      "name": "Mohd Saeed",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 11,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:37:37"
    },
    {
      "id": 14,
      "name": "Mohammad",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 11,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:38:49"
    },
    {
      "id": 15,
      "name": "Naseer Ahmad",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 14,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:40:08"
    },
    {
      "id": 16,
      "name": "Mohd Yaseen",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 14,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:41:02"
    },
    {
      "id": 17,
      "name": "Mohd Ameen",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Saraimeer",
      "photo": null,
      "bio": "",
      "fatherId": 14,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:41:41"
    },
    {
      "id": 18,
      "name": "Abdul Mannan",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 13,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:43:39"
    },
    {
      "id": 20,
      "name": "Mohd Khalid",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 13,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:51:26"
    },
    {
      "id": 21,
      "name": "Belal Ahmad",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 13,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:52:15"
    },
    {
      "id": 22,
      "name": "Habibur Rahman",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 13,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:53:33"
    },
    {
      "id": 23,
      "name": "Helal Ahmad",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 21,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:57:59"
    },
    {
      "id": 24,
      "name": "Maulana Abu Talib",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 21,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:59:00"
    },
    {
      "id": 25,
      "name": "Anisurrahman",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 21,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 10:59:37"
    },
    {
      "id": 26,
      "name": "Maulana Tahzeeb Anwar",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 21,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 11:00:12"
    },
    {
      "id": 27,
      "name": "Fauwaz Ahamd",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 21,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 11:00:46"
    },
    {
      "id": 29,
      "name": "Lamulumuddin",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 5,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 11:15:40"
    },
    {
      "id": 30,
      "name": "Haji Musa Sakin Lohia",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Lohia",
      "photo": null,
      "bio": "",
      "fatherId": 5,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 11:17:40"
    },
    {
      "id": 31,
      "name": "Dil Mohd",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 30,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 11:44:11"
    },
    {
      "id": 32,
      "name": "Haji Abdus Subhan",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 30,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 11:45:39"
    },
    {
      "id": 33,
      "name": "Haji Abdul Hameed",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 30,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 11:46:37"
    },
    {
      "id": 34,
      "name": "Haji Jumman",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 30,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 11:47:11"
    },
    {
      "id": 35,
      "name": "Azimullah",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 30,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 11:47:55"
    },
    {
      "id": 36,
      "name": "nahi pata VII",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 31,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 11:50:52"
    },
    {
      "id": 37,
      "name": "nahi pata VIII",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 31,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 11:51:22"
    },
    {
      "id": 38,
      "name": "Hafiz Abdus Samad",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 32,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 11:53:10"
    },
    {
      "id": 39,
      "name": "Abdul Sattar",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 33,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 11:54:09"
    },
    {
      "id": 40,
      "name": "Ibrahim",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 34,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 11:57:07"
    },
    {
      "id": 41,
      "name": "Abdul Gafoor",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 34,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 11:57:51"
    },
    {
      "id": 42,
      "name": "Mohd Shafique",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 34,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 11:58:19"
    },
    {
      "id": 43,
      "name": "Abdul Salam",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 34,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 11:59:16"
    },
    {
      "id": 44,
      "name": "Abdul Razique",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 34,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 12:00:53"
    },
    {
      "id": 45,
      "name": "Haji Zahir",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 40,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 12:02:13"
    },
    {
      "id": 46,
      "name": "Nahi Pata II",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 40,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 12:03:04"
    },
    {
      "id": 47,
      "name": "Mohd Bashir",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 43,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 12:06:37"
    },
    {
      "id": 48,
      "name": "nahi pata III",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 43,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 12:07:09"
    },
    {
      "id": 49,
      "name": "Mohd Anas",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 44,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 12:08:19"
    },
    {
      "id": 50,
      "name": "Abdus Sami",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 44,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 12:09:38"
    },
    {
      "id": 51,
      "name": "Salim",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "Aulad Koi Nahi",
      "fatherId": 35,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 12:15:15"
    },
    {
      "id": 52,
      "name": "Qasim",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 35,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 12:15:35"
    },
    {
      "id": 53,
      "name": "Mohd Nazir (I)",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 52,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-24 12:18:25"
    },
    {
      "id": 54,
      "name": "Akbar",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 8,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 10:14:19"
    },
    {
      "id": 55,
      "name": "Mohd Hasan urf Jinnu",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 8,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 10:16:07"
    },
    {
      "id": 56,
      "name": "Mohd Husain Urf Baap",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 8,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 10:18:56"
    },
    {
      "id": 57,
      "name": "Mohd Siddique",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 8,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 10:20:11"
    },
    {
      "id": 58,
      "name": "Abdul Hamid",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 8,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 10:21:35"
    },
    {
      "id": 59,
      "name": "Hafiz Mohd Usuf",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 8,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 10:22:12"
    },
    {
      "id": 60,
      "name": "Abdurrahman",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 54,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 10:25:35"
    },
    {
      "id": 61,
      "name": "Abdus Subhan",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 54,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 10:28:25"
    },
    {
      "id": 62,
      "name": "Abdullah",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 55,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 10:29:54"
    },
    {
      "id": 63,
      "name": "Abdul Gani",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 56,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 10:58:35"
    },
    {
      "id": 64,
      "name": "Faiz Umme Azad Rehmani",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 56,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:03:34"
    },
    {
      "id": 65,
      "name": "Abdul Gaffar",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 56,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:04:09"
    },
    {
      "id": 66,
      "name": "Mohd Nazir (II)",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 63,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:06:41"
    },
    {
      "id": 67,
      "name": "Mohd Nesar",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 63,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:07:13"
    },
    {
      "id": 68,
      "name": "Mohd Zubair",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 66,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:09:58"
    },
    {
      "id": 69,
      "name": "Mohd Ozair",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 66,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:13:26"
    },
    {
      "id": 70,
      "name": "Mohd Umair",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 66,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:13:52"
    },
    {
      "id": 71,
      "name": "Abdul Wahab",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 67,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:16:34"
    },
    {
      "id": 72,
      "name": "Abul Wafa",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 67,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:17:02"
    },
    {
      "id": 73,
      "name": "Molvi Aftab Ahmad",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 67,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:17:35"
    },
    {
      "id": 74,
      "name": "Hafiz Mushtaq Ahmad",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 67,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:18:59"
    },
    {
      "id": 75,
      "name": "Istiyak Ahmad",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 67,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:20:09"
    },
    {
      "id": 76,
      "name": "Neyaz Ahmad",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 67,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:20:49"
    },
    {
      "id": 77,
      "name": "Belal Ahmad",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 65,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:23:25"
    },
    {
      "id": 78,
      "name": "Maimuna Umme master Yaseen",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 57,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:29:42"
    },
    {
      "id": 79,
      "name": "Amena Umme Belal Ahmad",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 57,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:31:52"
    },
    {
      "id": 80,
      "name": "Nahi pata IV",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 57,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:34:48"
    },
    {
      "id": 81,
      "name": "Haji Abdul Azeez",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 57,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:37:20"
    },
    {
      "id": 82,
      "name": "Abdul Hameed",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 57,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:38:03"
    },
    {
      "id": 83,
      "name": "Mohd Idrees Azad Rehmani",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 81,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:43:27"
    },
    {
      "id": 84,
      "name": "Abdul Wahad",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 83,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:46:44"
    },
    {
      "id": 85,
      "name": "Abdul Wahid",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 83,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:47:57"
    },
    {
      "id": 86,
      "name": "nahi pata VI",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 81,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:51:17"
    },
    {
      "id": 87,
      "name": "Belal Ahmad",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 86,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:52:27"
    },
    {
      "id": 88,
      "name": "Basheer Ahmad",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 81,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:56:45"
    },
    {
      "id": 89,
      "name": "Haji Mohd Mustafa",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 88,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:58:13"
    },
    {
      "id": 90,
      "name": "Mohd Mujtba",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 88,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 11:59:29"
    },
    {
      "id": 93,
      "name": "Amir Ahmad",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 81,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 12:11:49"
    },
    {
      "id": 94,
      "name": "Zainul Abedin",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 93,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 12:21:38"
    },
    {
      "id": 95,
      "name": "Haji Abdul Kareem",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 59,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 12:31:00"
    },
    {
      "id": 96,
      "name": "Master Mohd Yaseen",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 95,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 12:43:53"
    },
    {
      "id": 97,
      "name": "Mohd Sheoeb (FCI- Adhikari)",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 96,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 12:49:31"
    },
    {
      "id": 98,
      "name": "Salahuddin",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 96,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 12:50:06"
    },
    {
      "id": 99,
      "name": "Razauddin",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 96,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 12:50:23"
    },
    {
      "id": 100,
      "name": "Suhail Ahmad",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 96,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 12:50:45"
    },
    {
      "id": 101,
      "name": "Mansur Raza",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 96,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-27 12:52:54"
    },
    {
      "id": 106,
      "name": "Yaar Mohd",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 2,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 10:44:53"
    },
    {
      "id": 107,
      "name": "Badlu",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 2,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 10:46:03"
    },
    {
      "id": 108,
      "name": "Wali Mohd",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 107,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:02:07"
    },
    {
      "id": 109,
      "name": "Bakas",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 107,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:05:14"
    },
    {
      "id": 110,
      "name": "Tahir",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 107,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:05:50"
    },
    {
      "id": 111,
      "name": "Abdurrahman (Lawald)",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 107,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:11:33"
    },
    {
      "id": 112,
      "name": "Abdul Haleem",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "AMilo",
      "photo": null,
      "bio": "",
      "fatherId": 107,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:12:33"
    },
    {
      "id": 113,
      "name": "Habibullah",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 108,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:15:21"
    },
    {
      "id": 114,
      "name": "Nasrullah",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 108,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:15:48"
    },
    {
      "id": 115,
      "name": "Haji Abdurraheem urf Aaiman",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 109,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:23:49"
    },
    {
      "id": 116,
      "name": "Saleem",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 109,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:24:12"
    },
    {
      "id": 117,
      "name": "Hafiz Shamzul haque",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 115,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:30:37"
    },
    {
      "id": 118,
      "name": "Abdul Qadir",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 115,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:31:35"
    },
    {
      "id": 119,
      "name": "Mohd Ibraheem",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 112,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:34:41"
    },
    {
      "id": 120,
      "name": "Abdul Hameed II",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 112,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:35:31"
    },
    {
      "id": 121,
      "name": "Mohd Ismail",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 112,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:36:23"
    },
    {
      "id": 122,
      "name": "Abdus Subhan (Bismil)",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 119,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:38:50"
    },
    {
      "id": 123,
      "name": "Zahirul Haque",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 119,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:46:00"
    },
    {
      "id": 124,
      "name": "Abdul Hafeez",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 120,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:49:49"
    },
    {
      "id": 125,
      "name": "Haji Abdur Rasheed",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 120,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:50:25"
    },
    {
      "id": 126,
      "name": "Abdul Majeed",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 120,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:51:19"
    },
    {
      "id": 127,
      "name": "naho pata",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 106,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:53:29"
    },
    {
      "id": 128,
      "name": "Jumman Sardar",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 127,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:54:20"
    },
    {
      "id": 129,
      "name": "Hakeem",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 127,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:54:35"
    },
    {
      "id": 130,
      "name": "Mohd Ameen II",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 128,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:55:30"
    },
    {
      "id": 131,
      "name": "Ibraheem Sakin (PKS)",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 129,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:57:16"
    },
    {
      "id": 132,
      "name": "Qasim II",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 129,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 11:57:57"
    },
    {
      "id": 133,
      "name": "Afroz Ahmad",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 98,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 12:02:12"
    },
    {
      "id": 134,
      "name": "Saifurrahman",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 98,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 12:03:42"
    },
    {
      "id": 135,
      "name": "Obaidurrahman",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 98,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 12:04:11"
    },
    {
      "id": 136,
      "name": "Anisurrahman II",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 98,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 12:04:34"
    },
    {
      "id": 137,
      "name": "Azhar Mokarim",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 98,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 12:05:03"
    },
    {
      "id": 138,
      "name": "Zafar M Warsi",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 98,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 12:05:48"
    },
    {
      "id": 139,
      "name": "Mohd Anas II",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 133,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 12:06:48"
    },
    {
      "id": 140,
      "name": "Mohd Amish",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 133,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 12:07:08"
    },
    {
      "id": 141,
      "name": "Sayem Rayyan",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 133,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 12:08:25"
    },
    {
      "id": 142,
      "name": "Shazan",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 133,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 12:08:57"
    },
    {
      "id": 143,
      "name": "Izaan",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 133,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 12:09:44"
    },
    {
      "id": 144,
      "name": "Yahya",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 133,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 12:10:50"
    },
    {
      "id": 145,
      "name": "Arshiyan",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 134,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 12:15:09"
    },
    {
      "id": 146,
      "name": "Hasan Saif",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 134,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 12:15:38"
    },
    {
      "id": 147,
      "name": "Mohd Iliyas",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 135,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 12:19:26"
    },
    {
      "id": 148,
      "name": "Jalaluddin",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 99,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 12:45:33"
    },
    {
      "id": 149,
      "name": "Arshad Saleem",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 99,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 12:46:23"
    },
    {
      "id": 150,
      "name": "Abdurrahman II",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 99,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 12:47:00"
    },
    {
      "id": 151,
      "name": "Mohd Aquib",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 99,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 12:47:22"
    },
    {
      "id": 152,
      "name": "Mohd Zayeem",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 99,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-28 12:48:03"
    },
    {
      "id": 153,
      "name": "Mohd Sharique",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 99,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:11:10"
    },
    {
      "id": 154,
      "name": "Sadique",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 99,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:11:37"
    },
    {
      "id": 155,
      "name": "Hafiz Mohd Ahmad",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 99,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:12:21"
    },
    {
      "id": 156,
      "name": "Ahmad Hussain",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 99,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:12:56"
    },
    {
      "id": 157,
      "name": "Saif Ali",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 99,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:13:18"
    },
    {
      "id": 158,
      "name": "nahi pata V",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 99,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:14:47"
    },
    {
      "id": 159,
      "name": "Child 1(Required)",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 148,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:17:16"
    },
    {
      "id": 160,
      "name": "Child 2 (Required)",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 148,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:17:36"
    },
    {
      "id": 161,
      "name": "Name Required",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 100,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:24:04"
    },
    {
      "id": 162,
      "name": "Master Mohd Shahid",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 97,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:27:10"
    },
    {
      "id": 163,
      "name": "Qaisar Raza",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 97,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:27:36"
    },
    {
      "id": 164,
      "name": "Mohd Shakeb",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "SultanPur",
      "photo": null,
      "bio": "",
      "fatherId": 97,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:28:14"
    },
    {
      "id": 165,
      "name": "Shaad",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 162,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:29:15"
    },
    {
      "id": 166,
      "name": "Daniyal Raza",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 163,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:29:51"
    },
    {
      "id": 167,
      "name": "Mohd Kaif",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 163,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:30:13"
    },
    {
      "id": 168,
      "name": "Nahi Pata",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 164,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:31:53"
    },
    {
      "id": 169,
      "name": "Abdullah II",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "",
      "photo": null,
      "bio": "",
      "fatherId": 89,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:45:39"
    },
    {
      "id": 170,
      "name": "Mohd Ismail II",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 89,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:46:06"
    },
    {
      "id": 171,
      "name": "Abdul Azeez",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 89,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:47:05"
    },
    {
      "id": 172,
      "name": "Nayeem",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 90,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:48:31"
    },
    {
      "id": 173,
      "name": "Maaz",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 90,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 07:49:05"
    },
    {
      "id": 174,
      "name": "Abul Qais",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 16,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 08:10:47"
    },
    {
      "id": 175,
      "name": "Razauddin II",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 16,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 08:11:36"
    },
    {
      "id": 176,
      "name": "Sabauddin",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 16,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 08:12:01"
    },
    {
      "id": 177,
      "name": "Noman",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 84,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 08:18:24"
    },
    {
      "id": 178,
      "name": "Athar",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 84,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 08:18:52"
    },
    {
      "id": 179,
      "name": "Hassan",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 84,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 08:19:42"
    },
    {
      "id": 180,
      "name": "Hannan",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 84,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 08:20:03"
    },
    {
      "id": 181,
      "name": "Abdul Mannan II",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 84,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 08:20:31"
    },
    {
      "id": 182,
      "name": "Gazi",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 84,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 08:21:43"
    },
    {
      "id": 183,
      "name": "Ragib",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 84,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 08:22:09"
    },
    {
      "id": 184,
      "name": "Molvi Haseeb",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 85,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 08:24:11"
    },
    {
      "id": 185,
      "name": "Abdur Raqib",
      "nameUr": null,
      "gender": "male",
      "dob": null,
      "dod": null,
      "birthplace": "Amilo",
      "photo": null,
      "bio": "",
      "fatherId": 85,
      "motherId": null,
      "spouseIds": [],
      "createdAt": "2026-07-29 08:24:45"
    }
  ],
  "users": [
    {
      "id": 1,
      "username": "admin",
      "name": "Administrator",
      "email": null,
      "role": "admin",
      "createdAt": "2026-07-24 06:27:14"
    }
  ],
  "gallery": [
    {
      "id": 2,
      "src": "7bcacca47355f2c4767399c4620eab8e.jpg",
      "caption": null,
      "uploadedAt": "2026-07-24 11:31:19"
    }
  ],
  "activityLog": [],
  "visitorCount": 0,
  "suggestions": []
} as AppState;
